project_id = "ceqfrgifrdxtbryjosmm"

[functions.chat]
verify_jwt = false

[functions.generate-cv]
verify_jwt = false

[functions.generate-matches]
verify_jwt = false

[functions.speech-to-text]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false
